//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETicaretDBEntities : DbContext
    {
        public ETicaretDBEntities()
            : base("name=ETicaretDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vw_aktif_urunler> vw_aktif_urunler { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<vw_kategoriler> vw_kategoriler { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<vw_suppliers> vw_suppliers { get; set; }
    }
}
