//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int SupplierID { get; set; }
        public string Photopath { get; set; }
        public string BrandName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
