//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string namesurname { get; set; }
        public string telephone { get; set; }
        public string invoiceaddress { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
