//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_aktif_urunler
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<long> Stock { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> VolumetricWeightValue { get; set; }
        public Nullable<int> VatNumber { get; set; }
        public Nullable<int> Highlights { get; set; }
        public Nullable<int> BestSellers { get; set; }
        public string OthersSee { get; set; }
        public string Notes { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string BrandName { get; set; }
    }
}
